#!/usr/bin/env node

/**
 * Module dependencies.
 */
var program = require('commander');
var CommanderUtils = require('../');

var packageJson = require('../package.json');
var programUtils = new CommanderUtils(program, packageJson);
programUtils.setVersion();
programUtils.addLogOptions();
programUtils.commandUpdate({packageJsonUrl: 'https://raw.github.com/subtub/commander-utils/master/package.json',
                            installUrl: 'https://github.com/subtub/commander-utils/tarball/master'});

program
  .option('-s, --subtub', 'subtub says hello')
  .parse(process.argv);

programUtils.checkLogOptions();
//programUtils.ifNoArgsShowHelp();


if (program.subtub) {
	programUtils.log.info('Hello World');
};
