#!/usr/bin/env node

/**
 * This example integrates some package.json information.
 * Also add an example command and description to the --help output.
 */


/**
 * Module dependencies.
 */
var program = require('commander');
var CommanderUtils = require('../');
var pkg = require('../package.json');

/**
 * Initialize the commander-utils module.
 */
CommanderUtils(program, pkg);

/**
 * Add an example command to the main --help page.
 */
program.addExamples([{description: 'description of the example',
                      command:     'the command'}]);

/**
 * Add an option to the commandline interface.
 */
program
  .option('-f, --foo', 'foo stuff')

/**
 * Parse the arguments.
 */
program.parseUtils(process.argv);

/**
 * If the --foo option is active, do someting.
 */
if (program.foo) {
  program.log.info('Foo to the Box');
};
