#!/usr/bin/env node

/**
 * Module dependencies.
 */
var program = require('commander');
var CommanderUtils = require('../');
var pkg = require('../package.json');

/**
 * Initialize the commander-utils module.
 */
CommanderUtils(program, pkg);
program.initUtils();

/**
 * Add an option to the commandline interface.
 */
program
  .option('-b, --baz', 'baz stuff')

/**
 * Parse the arguments.
 */
program
  .parse(process.argv)
  .parseUtils();

/**
 * If the --baz option is active, do someting.
 */
if (program.baz) {
  program.log.info('Baz to the Box');
};
